/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NoiseGate {
  constructor(threshold: number)
  process(data: Array<number>): Array<number>
  processAudioFast(data: Float32Array): void
}
