name: Remote Deploy

on:
  workflow_dispatch:
    # empty to allow manual trigger
  push:
    branches:
      - jarvis-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gchat/GeeGeeChat/chat4gamers/apps/server
            git fetch origin jarvis-deploy
            git reset --hard origin/jarvis-deploy
            yarn install
            yarn build
            sudo systemctl restart geechat-backend